- name: Stop instances
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./vars/vars.yml
  tasks:
    - name: Stop the EC2 instances
      ec2:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        instance_ids: "{{ item.ids }}"
        region: "{{ item.region }}"
        state: stopped
        wait: True
        vpc_subnet_id: subnet-29e63245
        assign_public_ip: yes
      register: ec2
      loop: "{{ ec2_instances_list }}"
    - debug: msg="ec2 {{ ec2.results }}"
    - name: Stop the Azure instances
      azure_rm_virtualmachine:
        resource_group: "{{ az_resource_group }}"
        name: "{{ item }}"
        allocated: no
      register: az
      loop: "{{ az_instances_list }}"
    - debug: msg="az {{ az.results }}"
