providers:
  aws:
    us-east-1:
      - i-0ffc735330aa8634a
    eu-central-1:
      - i-04ccbdfc124d91116

  azure:
    cloud-bench:
      - m1-cb
      - m2-cb

  gcp:
    europe-west3-a:
      - e2-1
      - e2-2